services:
  fe:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=http://be:4000
      - NUXT_PUBLIC_WS_URL=http://be:4000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - be
    restart: unless-stopped

  be:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/game_db
    volumes:
      - ./:/app
      - /app/backend/node_modules
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
