services:
  fe:
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_BASE=http://be:4000
      - NUXT_PUBLIC_WS_URL=http://be:4000
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped

  be:
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/game_db
    volumes:
      - ./:/app
      - /app/backend/node_modules
    ports:
      - "4000:4000"
    restart: unless-stopped

  db:
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=game_db
    ports:
      - "5432:5432"
    restart: unless-stopped
